# Generated by Django 5.0.6 on 2024-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.CharField(default='круто', max_length=25),
        ),
    ]
