# Generated by Django 5.0.6 on 2024-06-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_video_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
    ]
