# Generated by Django 5.0.6 on 2024-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0008_remove_video_post_post_user_post_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
