# Generated by Django 5.0.6 on 2024-07-10 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0010_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
