main_page_template = 'index.html'
login_page_template = 'login.html'
reg_page_template = 'reg_page.html'
reg_page_done_template = 'reg_done.html'
upload_video_template = 'upload_video.html'
user_page_template = 'userpage.html'
