main_page_template = 'index.html'
login_page_template = 'login.html'
reg_page_template = 'registration/reg_page.html'
upload_video_template = 'upload_video.html'
user_page_template = 'userpage.html'
# only_header_page = 'header.html'
base_page = 'base.html'
