# Generated by Django 5.0.6 on 2024-07-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
