# Generated by Django 6.0 on 2026-01-02 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_customuser_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.video', verbose_name='Понравившееся видео')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
